[package]
name = "misc"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"

[features]
# 1. By default, enable the 'dev' feature (Fast Compile)
default = ["dev"] 

# 2. The 'dev' feature triggers Bevy's dynamic linking
dev = ["bevy/dynamic_linking"]
